import sys, unittest
from pathlib import Path

import jax
import jax.numpy as jnp

PYHAICS_PATH = Path(__file__).parents[2]
sys.path.append(str(PYHAICS_PATH))

import pyHaiCS as haics
from pyHaiCS.utils.test import HiddenPrints

class TestRWMH(unittest.TestCase):
    """
    Unit tests for the RWMH sampler in pyHaiCS.
    - This class tests both single and multi-chain sampling methods.
    - It uses a simple quadratic potential function as the target distribution.
    - The tests check the output shape of the samples generated by the sampler.
    - The potential function is defined as a static method within the class.
    - The tests are wrapped in a HiddenPrints context manager to suppress output during testing.
    """

    @staticmethod
    def quadratic_potential(x):
        return 0.5 * jnp.sum(x ** 2)

    def setUp(self):
        self.x_init = jnp.array([0.0])
        self.n_samples = 1000
        self.burn_in = 100
        self.step_size = 0.5
        self.key = jax.random.PRNGKey(0)
        self.potential = self.quadratic_potential

    @HiddenPrints
    def test_single_chain_output_shape(self):
        samples = haics.samplers.basic_mcmc._single_chain_RWMH(
            self.x_init,
            self.n_samples,
            self.burn_in,
            self.step_size,
            self.potential,
            self.key
        )
        self.assertEqual(samples.shape, (self.n_samples, 1))

    @HiddenPrints
    def test_multi_chain_output_shape(self):
        n_chains = 4
        samples = haics.samplers.basic_mcmc.RWMH(
            self.x_init,
            (),
            self.n_samples,
            self.burn_in,
            self.step_size,
            self.potential,
            n_chains=n_chains,
            RNG_key=123
        )
        self.assertEqual(samples.shape, (n_chains, self.n_samples, 1))

if __name__ == '__main__':
    unittest.main()
