import sys, unittest
from pathlib import Path

import jax
import jax.numpy as jnp

PYHAICS_PATH = Path(__file__).parents[2]
sys.path.append(str(PYHAICS_PATH))
sys.path.insert(0, str(PYHAICS_PATH))

import pyHaiCS as haics
from pyHaiCS.utils.test import HiddenPrints

class TestRWMH(unittest.TestCase):
    """
    Unit tests for the RWMH sampler in pyHaiCS.
    - This class tests both single and multi-chain sampling methods.
    - It uses a simple quadratic potential function as the target distribution.
    - The tests check the output shape of the samples generated by the sampler.
    - The potential function is defined as a static method within the class.
    - The tests are wrapped in a HiddenPrints context manager to suppress output during testing.
    """

    @staticmethod
    def quadratic_potential(x):
        return 0.5 * jnp.sum(x ** 2)

    def setUp(self):
        self.x_init = jnp.array([0.0])
        self.n_samples = 100
        self.burn_in = 100
        self.step_size = 0.5
        self.key = jax.random.PRNGKey(0)
        self.potential = self.quadratic_potential

    @HiddenPrints
    def test_single_chain_output_shape(self):
        samples = haics.samplers.basic_mcmc._single_chain_RWMH(
            self.x_init,
            self.n_samples,
            self.burn_in,
            self.step_size,
            self.potential,
            self.key
        )
        self.assertEqual(samples.shape, (self.n_samples, 1))

    @HiddenPrints
    def test_multi_chain_output_shape(self):
        n_chains = 4
        samples = haics.samplers.basic_mcmc.RWMH(
            self.x_init,
            (),
            self.n_samples,
            self.burn_in,
            self.step_size,
            self.potential,
            n_chains=n_chains,
            RNG_key=123
        )
        self.assertEqual(samples.shape, (n_chains, self.n_samples, 1))

class TestHMC(unittest.TestCase):
    """
    Unit tests for the HMC sampler in pyHaiCS.
    Tests both single and multi-chain sampling for shape correctness.
    """

    @staticmethod
    def quadratic_potential(x):
        return 0.5 * jnp.sum(x**2)

    @staticmethod
    def quadratic_potential_grad(x):
        return x

    def setUp(self):
        self.x_init = jnp.array([0.0])
        self.n_samples = 10
        self.burn_in = 10
        self.step_size = 0.1
        self.n_steps = 5
        self.mass_matrix = jnp.eye(1)
        self.key = jax.random.PRNGKey(0)
        self.integrator = haics.integrators.integrators.VerletIntegrator()
        self.potential = self.quadratic_potential
        self.potential_grad = self.quadratic_potential_grad

    @HiddenPrints
    def test_single_chain_output_shape(self):
        samples = haics.samplers.hamiltonian._single_chain_HMC(
            self.x_init,
            self.n_samples,
            self.burn_in,
            self.step_size,
            self.n_steps,
            self.potential,
            self.potential_grad,
            self.mass_matrix,
            self.integrator,
            self.key
        )
        self.assertEqual(samples.shape, (self.n_samples, 1))

    @HiddenPrints
    def test_multi_chain_output_shape(self):
        n_chains = 3
        samples = haics.samplers.hamiltonian.HMC(
            self.x_init,
            (),
            self.n_samples,
            self.burn_in,
            self.step_size,
            self.n_steps,
            self.potential,
            self.mass_matrix,
            integrator=self.integrator,
            n_chains=n_chains,
            RNG_key=123
        )
        self.assertEqual(samples.shape, (n_chains, self.n_samples, 1))

    @HiddenPrints
    def test_all_integrators(self):
        integrators = [
            haics.integrators.integrators.VerletIntegrator(),
            haics.integrators.integrators.VV_2(),
            haics.integrators.integrators.ME_2(),
            haics.integrators.integrators.VV_3(),
            haics.integrators.integrators.ME_3(),
            haics.integrators.integrators.MSSI_2(b=0.3),
            haics.integrators.integrators.MSSI_3(a=0.2, b=0.3),
        ]
        for integrator in integrators:
            with self.subTest(integrator=type(integrator).__name__):
                samples = haics.samplers.hamiltonian.HMC(
                    self.x_init,
                    (),
                    self.n_samples,
                    self.burn_in,
                    self.step_size,
                    self.n_steps,
                    self.potential,
                    self.mass_matrix,
                    integrator=integrator,
                    n_chains=2,
                    RNG_key=42
                )
                self.assertEqual(samples.shape, (2, self.n_samples, 1))

    @HiddenPrints
    def test_invalid_xinit_shape(self):
        bad_x_init = jnp.array([[0.0, 0.0]])  # Wrong shape: 2D instead of 1D
        with self.assertRaises(Exception):
            with HiddenPrints():
                haics.samplers.hamiltonian.HMC(
                    bad_x_init,
                    (),
                    self.n_samples,
                    self.burn_in,
                    self.step_size,
                    self.n_steps,
                    self.potential,
                    self.mass_matrix,
                    n_chains=2,
                    RNG_key=123
                )

    @HiddenPrints
    def test_burnin_zero(self):
        samples = haics.samplers.hamiltonian.HMC(
            self.x_init,
            (),
            self.n_samples,
            burn_in=0,
            step_size=self.step_size,
            n_steps=self.n_steps,
            potential=self.potential,
            mass_matrix=self.mass_matrix,
            n_chains=2,
            RNG_key=7
        )
        self.assertEqual(samples.shape, (2, self.n_samples, 1))

    @HiddenPrints
    def test_gradient_consistency(self):
        x = jnp.array([1.5])
        grad_auto = jax.grad(self.potential)(x)
        grad_manual = self.potential_grad(x)
        self.assertTrue(jnp.allclose(grad_auto, grad_manual))

class TestGHMC(unittest.TestCase):
    @staticmethod
    def quadratic_potential(x):
        return 0.5 * jnp.sum(x**2)

    def setUp(self):
        self.x_init = jnp.array([0.0])
        self.n_samples = 10
        self.burn_in = 5
        self.step_size = 0.1
        self.n_steps = 3
        self.mass_matrix = jnp.eye(1)
        self.momentum_noise = 0.5
        self.key = jax.random.PRNGKey(0)
        self.potential = self.quadratic_potential
        self.integrator = haics.integrators.integrators.VerletIntegrator()

    @HiddenPrints
    def test_multi_chain_output_shape(self):
        samples = haics.samplers.hamiltonian.GHMC(
            self.x_init,
            (),
            self.n_samples,
            self.burn_in,
            self.step_size,
            self.n_steps,
            self.potential,
            self.mass_matrix,
            self.momentum_noise,
            integrator=self.integrator,
            n_chains=3,
            RNG_key=0
        )
        self.assertEqual(samples.shape, (3, self.n_samples, 1))

class TestMALA(unittest.TestCase):
    @staticmethod
    def quadratic_potential(x):
        return 0.5 * jnp.sum(x**2)

    def setUp(self):
        self.x_init = jnp.array([0.0])
        self.n_samples = 10
        self.burn_in = 5
        self.step_size = 0.1
        self.mass_matrix = jnp.eye(1)
        self.potential = self.quadratic_potential
        self.integrator = haics.integrators.integrators.VerletIntegrator()

    @HiddenPrints
    def test_multi_chain_output_shape(self):
        samples = haics.samplers.hamiltonian.MALA(
            self.x_init,
            (),
            self.n_samples,
            self.burn_in,
            self.step_size,
            self.potential,
            self.mass_matrix,
            integrator=self.integrator,
            n_chains=3,
            RNG_key=1
        )
        self.assertEqual(samples.shape, (3, self.n_samples, 1))

class TestL2MC(unittest.TestCase):
    @staticmethod
    def quadratic_potential(x):
        return 0.5 * jnp.sum(x**2)

    def setUp(self):
        self.x_init = jnp.array([0.0])
        self.n_samples = 10
        self.burn_in = 5
        self.step_size = 0.1
        self.mass_matrix = jnp.eye(1)
        self.momentum_noise = 0.5
        self.potential = self.quadratic_potential
        self.integrator = haics.integrators.integrators.VerletIntegrator()

    @HiddenPrints
    def test_multi_chain_output_shape(self):
        samples = haics.samplers.hamiltonian.L2MC(
            self.x_init,
            (),
            self.n_samples,
            self.burn_in,
            self.step_size,
            self.potential,
            self.mass_matrix,
            self.momentum_noise,
            integrator=self.integrator,
            n_chains=3,
            RNG_key=2
        )
        self.assertEqual(samples.shape, (3, self.n_samples, 1))

class TestMDMC(unittest.TestCase):
    @staticmethod
    def quadratic_potential(x):
        return 0.5 * jnp.sum(x**2)

    def setUp(self):
        self.x_init = jnp.array([0.0])
        self.n_samples = 10
        self.burn_in = 5
        self.step_size = 0.1
        self.n_steps = 3
        self.mass_matrix = jnp.eye(1)
        self.potential = self.quadratic_potential
        self.integrator = haics.integrators.integrators.VerletIntegrator()

    @HiddenPrints
    def test_multi_chain_output_shape(self):
        samples = haics.samplers.hamiltonian.MDMC(
            self.x_init,
            (),
            self.n_samples,
            self.burn_in,
            self.step_size,
            self.n_steps,
            self.potential,
            self.mass_matrix,
            integrator=self.integrator,
            n_chains=3,
            RNG_key=3
        )
        self.assertEqual(samples.shape, (3, self.n_samples, 1))

class TestSLDMC(unittest.TestCase):
    @staticmethod
    def quadratic_potential(x):
        return 0.5 * jnp.sum(x**2)

    def setUp(self):
        self.x_init = jnp.array([0.0])
        self.n_samples = 10
        self.burn_in = 5
        self.step_size = 0.1
        self.n_steps = 3
        self.mass_matrix = jnp.eye(1)
        self.friction = 0.4
        self.potential = self.quadratic_potential
        self.integrator = haics.integrators.integrators.VerletIntegrator()

    @HiddenPrints
    def test_multi_chain_output_shape(self):
        samples = haics.samplers.hamiltonian.SLDMC(
            self.x_init,
            (),
            self.n_samples,
            self.burn_in,
            self.step_size,
            self.n_steps,
            self.potential,
            self.mass_matrix,
            self.friction,
            integrator=self.integrator,
            n_chains=3,
            RNG_key=4
        )
        self.assertEqual(samples.shape, (3, self.n_samples, 1))

class TestNonImplementedSamplers(unittest.TestCase):
    @HiddenPrints
    def test_mhmc_raises_not_implemented(self):
        with self.assertRaises(NotImplementedError):
            haics.samplers.hamiltonian.MHMC()

    @HiddenPrints
    def test_rmhmc_raises_not_implemented(self):
        with self.assertRaises(NotImplementedError):
            haics.samplers.hamiltonian.RMHMC()

if __name__ == '__main__':
    unittest.main()
